<a href="https://colab.research.google.com/github/gakbn/ESCB-AngelGabrielAndradeAmezcua/blob/main/Lab13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [14]:
from sklearn.metrics import ( accuracy_score,
                             confusion_matrix,
                             classification_report,
                             ConfusionMatrixDisplay  )

In [15]:
from numpy import load
from sklearn.datasets import load_iris
#Cargamos el dataset iris
iris=load_iris(as_frame = True)

In [16]:

print (iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [17]:
#Dataframe
dfIris = iris.frame

In [18]:
dfIris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0





#Exploracion de conjunto de datos



In [19]:
dfIris.shape

(150, 5)

In [20]:
dfIris.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

In [21]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [22]:
#Renombrar la columna target

dfIris.rename(columns= {"target": "especie" }, inplace=True)

In [22]:
dfIris["especie"]= dfIris ["especie"].map({
    0: "setosa",
    1: "versicolor",
    2: "virginica"
})

In [23]:
dfIris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),especie
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [24]:
dfIris.tail()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),especie
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2


#Identeficar variables predictoras y variables objetivo


In [25]:
#variables predictora
X = dfIris.drop(columns=["especie"])

In [26]:
print("Variables predictoras")
(X.columns)

Variables predictoras


Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [27]:
#Variable objetivo
y = dfIris["especie"]

In [28]:
print("Variable objetivo")
(y.name)

Variable objetivo


'especie'

# Dividir los datos en prueba y entrenamiento

# 80% para entrenamiento
# 20% para prueba

In [31]:
X_Train, X_Test, y_Train, y_Test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [33]:
print("X_train", X_Train.shape)
print("X_test", X_Test.shape)
print("y_train", y_Train.shape)
print("y_test", y_Test.shape)

X_train (120, 4)
X_test (30, 4)
y_train (120,)
y_test (30,)


# Escalado de variables


In [34]:
scaler = StandardScaler()

In [35]:
# escalamos las variables
X_Train_escalado = scaler.fit_transform(X_Train)
X_Test_escalado = scaler.transform(X_Test)

In [36]:
print ("Sin escalar")
print (X_Train.head())
print ("Escalado")
print (X_Train_escalado[0:5])

Sin escalar
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
8                  4.4               2.9                1.4               0.2
106                4.9               2.5                4.5               1.7
76                 6.8               2.8                4.8               1.4
9                  4.9               3.1                1.5               0.1
89                 5.5               2.5                4.0               1.3
Escalado
[[-1.72156775 -0.33210111 -1.34572231 -1.32327558]
 [-1.12449223 -1.22765467  0.41450518  0.6517626 ]
 [ 1.14439475 -0.5559895   0.58484978  0.25675496]
 [-1.12449223  0.11567567 -1.28894078 -1.45494479]
 [-0.40800161 -1.22765467  0.13059752  0.12508575]]


# Entrenamiento del modelo KNM

En esta prueba utilizaremos k = 3

In [37]:
modelo = KNeighborsClassifier(n_neighbors=3)

In [38]:
modelo.fit(X_Train_escalado, y_Train)

KNeighborsClassifier(n_neighbors=3)